services:
  app:
    image: phonebook-frontend

  server:
    image: todo-backend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80 # this is needed
    container_name: reverse-proxy-prod
    depends_on:
      - app
